services:
  isaac-sim:
    image: nvcr.io/nvidia/isaac-sim:6.0.1
    container_name: isaac-sim-groot
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - ACCEPT_EULA=Y
      # WebRTC用のパブリックIP（起動スクリプトから注入）
      - PUBLIC_IP=${PUBLIC_IP}
    volumes:
      # ホスト側のWorkspaceとコンテナ内を結合
      - ../IsaacLab:/workspace/IsaacLab
      - .:/workspace/g1-handover-project
    entrypoint: ["/bin/bash", "/workspace/g1-handover-project/scripts/container_entrypoint.sh"]
    # エントリーポイントの後に実行されるデフォルトコマンド
    command: >
      /workspace/isaac-sim/runheadless.sh
      --/exts/omni.kit.livestream.app/primaryStream/publicIp=${PUBLIC_IP}
      --/exts/omni.kit.livestream.app/primaryStream/signalPort=49100
      --/exts/omni.kit.livestream.app/primaryStream/streamPort=47998