[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "g1_handover"
version = "0.1.0"
description = "Unitree G1 Handover Task using Isaac Lab"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "scipy>=1.11"
]

[tool.setuptools.packages.find]
where = ["src"]